// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import (
	ads "homework10/internal/entities/ads"

	context "context"

	mock "github.com/stretchr/testify/mock"
)

// App is an autogenerated mock type for the App type
type App struct {
	mock.Mock
}

// ChangeAdStatus provides a mock function with given fields: ctx, adId, userId, newStatus
func (_m *App) ChangeAdStatus(ctx context.Context, adId int64, userId int64, newStatus bool) (*ads.Ad, error) {
	ret := _m.Called(ctx, adId, userId, newStatus)

	var r0 *ads.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, bool) (*ads.Ad, error)); ok {
		return rf(ctx, adId, userId, newStatus)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, bool) *ads.Ad); ok {
		r0 = rf(ctx, adId, userId, newStatus)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ads.Ad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, bool) error); ok {
		r1 = rf(ctx, adId, userId, newStatus)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// CreateAd provides a mock function with given fields: ctx, title, text, id
func (_m *App) CreateAd(ctx context.Context, title string, text string, id int64) (*ads.Ad, error) {
	ret := _m.Called(ctx, title, text, id)

	var r0 *ads.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) (*ads.Ad, error)); ok {
		return rf(ctx, title, text, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int64) *ads.Ad); ok {
		r0 = rf(ctx, title, text, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ads.Ad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string, string, int64) error); ok {
		r1 = rf(ctx, title, text, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteAd provides a mock function with given fields: ctx, adId, userId
func (_m *App) DeleteAd(ctx context.Context, adId int64, userId int64) error {
	ret := _m.Called(ctx, adId, userId)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64) error); ok {
		r0 = rf(ctx, adId, userId)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAdById provides a mock function with given fields: ctx, id
func (_m *App) GetAdById(ctx context.Context, id int64) (*ads.Ad, error) {
	ret := _m.Called(ctx, id)

	var r0 *ads.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64) (*ads.Ad, error)); ok {
		return rf(ctx, id)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64) *ads.Ad); ok {
		r0 = rf(ctx, id)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ads.Ad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64) error); ok {
		r1 = rf(ctx, id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAdsByTitle provides a mock function with given fields: ctx, title
func (_m *App) GetAdsByTitle(ctx context.Context, title string) ([]*ads.Ad, error) {
	ret := _m.Called(ctx, title)

	var r0 []*ads.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) ([]*ads.Ad, error)); ok {
		return rf(ctx, title)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) []*ads.Ad); ok {
		r0 = rf(ctx, title)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ads.Ad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, title)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAll provides a mock function with given fields: ctx, filters
func (_m *App) GetAll(ctx context.Context, filters ads.Filters) ([]*ads.Ad, error) {
	ret := _m.Called(ctx, filters)

	var r0 []*ads.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, ads.Filters) ([]*ads.Ad, error)); ok {
		return rf(ctx, filters)
	}
	if rf, ok := ret.Get(0).(func(context.Context, ads.Filters) []*ads.Ad); ok {
		r0 = rf(ctx, filters)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]*ads.Ad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, ads.Filters) error); ok {
		r1 = rf(ctx, filters)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateAd provides a mock function with given fields: ctx, adId, userId, title, text
func (_m *App) UpdateAd(ctx context.Context, adId int64, userId int64, title string, text string) (*ads.Ad, error) {
	ret := _m.Called(ctx, adId, userId, title, text)

	var r0 *ads.Ad
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, string) (*ads.Ad, error)); ok {
		return rf(ctx, adId, userId, title, text)
	}
	if rf, ok := ret.Get(0).(func(context.Context, int64, int64, string, string) *ads.Ad); ok {
		r0 = rf(ctx, adId, userId, title, text)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*ads.Ad)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context, int64, int64, string, string) error); ok {
		r1 = rf(ctx, adId, userId, title, text)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewApp interface {
	mock.TestingT
	Cleanup(func())
}

// NewApp creates a new instance of App. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewApp(t mockConstructorTestingTNewApp) *App {
	mock := &App{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
