# For more information see: https://github.com/marketplace/actions/repo-lockdown

name: 'Repo Lockdown'

on:
  pull_request_target:
    types: opened
  schedule:
    - cron: '0 11 * * 2'

permissions:
  pull-requests: write

jobs:
  action:
    runs-on: ubuntu-latest
    steps:
      - uses: dessant/repo-lockdown@v3
        exclude-pr-labels: 'pinned'
        pr-comment: 'all homework is checked inside pull requests in your personal repositories!'
